CREATE TABLE IF NOT EXISTS patron (
  PatronID INT AUTO_INCREMENT PRIMARY KEY,
  PatronName VARCHAR(100) NOT NULL,
  Email VARCHAR(150) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_order (
  TicketID INT AUTO_INCREMENT PRIMARY KEY,
  PatronID INT NOT NULL,
  ScheduleID INT NOT NULL,
  Quantity INT NOT NULL,
  TicketPrice DECIMAL(10,2) NOT NULL,
  TotalAmount DECIMAL(10,2) NOT NULL,
  PaymentName VARCHAR(100) NOT NULL,
  CardLast4 VARCHAR(4) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PatronID) REFERENCES patron(PatronID) ON DELETE CASCADE,
  FOREIGN KEY (ScheduleID) REFERENCES schedule(ScheduleID) ON DELETE CASCADE
);
